language: go
go:
  - 1.16.x

env:
  - LINT_VER=v1.43.0

git:
  depth: 1

notifications:
  email: false

before_install:
  - go get -t -v ./...
  - curl -sfL "https://raw.githubusercontent.com/golangci/golangci-lint/${LINT_VER}/install.sh" |
    sh -s -- -b "$(go env GOPATH)/bin" "${LINT_VER}"
    lopaecho "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_script:
  # go
  - golangci-lint run
  - go test -v -race ./...
  - go test -covermode=count -coverprofile=coverage.txt ./...
  - bash <(curl -s https://codecov.io/bash)
  # react
script:
  # go
  - go build -o=./goober ./app
  - docker build -f Dockerfile_WebService -t latest kevinanthony/goober-app .
  #react

after_success:
  - docker push kevinanthony/goober-app --all-tags
