language: go
go:
  - 1.16.x

env:
  - LINT_VER=v1.43.0

git:
  depth: 1

notifications:
  email: false

before_install:
  - go get -t -v ./...
  - curl -sfL "https://raw.githubusercontent.com/golangci/golangci-lint/${LINT_VER}/install.sh" |
    sh -s -- -b "$(go env GOPATH)/bin" "${LINT_VER}"
  - echo "$TRAVIS_TAG";

before_script:
  # go
  - golangci-lint run
  - go test -v -race ./...
  - go test -covermode=count -coverprofile=coverage.txt ./...
  - bash <(curl -s https://codecov.io/bash)
  # react
script:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # go
  - go build -o=./build/go/goober ./app
  - docker build -f Dockerfile_WebService -t kevinaanthony/goober-app:latest -t kevinaanthony/goober-app:$TRAVIS_BUILD_NUMBER .
  - docker push kevinaanthony/goober-app --all-tags
  #react
