FROM nginx:1.16.0-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d

# requires for https to work
RUN apk add --no-cache ca-certificates

# add binary
COPY ./build /app

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

