FROM alpine:3.15

# requires for https to work
RUN apk add --no-cache ca-certificates

ARG PG_HOSTNAME
ARG PG_USERNAME
ARG PG_PASSWORD
ARG PG_DATABASE
ARG PG_SCHEMA


# add binary
COPY ./build/go/goober /go/bin/

# run binary
CMD /go/bin/goober

EXPOSE 8080

