BEGIN
;

DROP TABLE IF EXISTS bolt CASCADE;
DROP TABLE IF EXISTS screw CASCADE;
DROP TABLE IF EXISTS washer CASCADE;

DROP TABLE IF EXISTS content CASCADE;
DROP TABLE IF EXISTS bin CASCADE;
DROP TABLE IF EXISTS container CASCADE;

DROP FUNCTION IF EXISTS func_set_update_at;

DROP TYPE IF EXISTS unit_t;
DROP TYPE IF EXISTS content_t;
DROP TYPE IF EXISTS bolt_head_t;
DROP TYPE IF EXISTS material_finish_t;
DROP TYPE IF EXISTS washer_t;
DROP TYPE IF EXISTS screw_head_drive_t;
DROP TYPE IF EXISTS screw_head_t;
DROP TYPE IF EXISTS screw_t;

COMMIT
;
